on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies (SQLite)
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev pkg-config

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Add GOPATH/bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL is not set"
            exit 1
          fi
          goose -dir ./sql/schema sqlite3 "$DATABASE_URL" up

      - name: Build Docker image
        run: docker build -t my-app:${{ github.sha }} .