name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      # Install goose (migration CLI)
      - name: Install goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
          echo "goose installed to $(go env GOPATH)/bin"

      - name: Build binary
        run: ./scripts/buildprod.sh

      - name: Build and Push Docker image
        run: docker build -t russe98/notely:latest .

      # Run DB migrations (inject DATABASE_URL ONLY here)
      - name: Run DB migrations with goose
        run: ./scripts/migrateup.sh
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

